name: attendance-time-check

on:
  #  schedule:
  #    - cron: '0 2,13 * * 1-5'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Chrome Driver
        run: |
          CHROME_VERSION_PATH=LATEST_RELEASE_$(google-chrome --version | cut -d " " -f 3 | cut -d "." -f 1-3)
          CHROME_DRIVER_VERSION_PATH=$(wget -qO- "https://chromedriver.storage.googleapis.com/${CHROME_VERSION_PATH}")
          CHROME_DRIVER_LOCATION_PATH="https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION_PATH/chromedriver_linux64.zip"
          mkdir /chromedriver
          wget -O chromedriver_linux64.zip $CHROME_DRIVER_LOCATION_PATH
          unzip chromedriver_linux64.zip
          echo "/chromedriver" >> $GITHUB_PATH

      - name: Execute attendance-checker-for-king-of-time script
        run: |
          yarn add attendance-checker-for-king-of-time@^1
          node ./node_modules/attendance-checker-for-king-of-time/dist/index.js
